name: Analyze feeds (VANTA AI)

on:
  workflow_run:
    workflows: ["RSS Scan"]   # must match the name in rss.yml
    types: [completed]
  workflow_dispatch:
    inputs:
      run_date:
        description: "YYYY-MM-DD (UTC). Leave empty to auto-detect."
        required: false
        default: ""

permissions:
  contents: write

jobs:
  analyze:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install requirements
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Detect UTC date if not provided
        id: date
        run: |
          if [ -n "${{ inputs.run_date }}" ]; then
            echo "date=${{ inputs.run_date }}" >> $GITHUB_OUTPUT
          else
            UTC_DATE=$(date -u +'%Y-%m-%d')
            echo "date=$UTC_DATE" >> $GITHUB_OUTPUT
          fi

      - name: Run analysis
        run: |
          set -Eeuo pipefail
          python analyze.py --date "${{ steps.date.outputs.date }}"
