name: RSS Scan

on:
  schedule:
    - cron: "*/15 * * * *"   # every 15 minutes (UTC)
  workflow_dispatch: {}       # allow manual runs

permissions:
  contents: write

concurrency:
  group: rss-scan
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      INCLUDE_GENERAL: "true"   # set to "true" if you add general_feeds.txt

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Ensure output dirs
        run: |
          mkdir -p docs data/processed data/raw

      - name: Run RSS scraper
        run: python scrape.py

      - name: Commit changes
        shell: bash
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          # Stage what downstream workflows need (and docs if you publish them)
          git add docs data/processed data/raw || true
          # Only commit if there are staged changes
          if ! git diff --cached --quiet; then
            git commit -m "update rss $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          else
            echo "No changes to commit."
          fi
